# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\"\x9e\x02\n\x0bHeadMessage\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_type\x18\x02 \x01(\x05\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x0f\n\x07role_id\x18\x04 \x01(\x03\x12\x14\n\x0cservice_name\x18\x05 \x01(\t\x12\r\n\x05group\x18\x06 \x01(\t\x12\x13\n\x0binstance_id\x18\x07 \x01(\t\x12\r\n\x05token\x18\x08 \x01(\t\x12\x12\n\nrequest_id\x18\t \x01(\t\x12\x34\n\x10service_msg_type\x18\n \x01(\x0e\x32\x1a.common.ServiceMessageType\x12\x1d\n\x15load_balance_strategy\x18\x0b \x01(\t\x12\x11\n\ttimestamp\x18\x0c \x01(\x03\"\x8e\x01\n\x0bGameMessage\x12%\n\x08msg_head\x18\x01 \x01(\x0b\x32\x13.common.HeadMessage\x12%\n\x08msg_type\x18\x02 \x01(\x0e\x32\x13.common.MessageType\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x0f\n\x07msg_tap\x18\x04 \x01(\t\x12\x0f\n\x07game_id\x18\x05 \x01(\x05\"\x92\x01\n\x13GameMessageResponse\x12%\n\x08msg_head\x18\x01 \x01(\x0b\x32\x13.common.HeadMessage\x12\x0b\n\x03ret\x18\x02 \x01(\x05\x12\x10\n\x06reason\x18\x03 \x01(\tH\x00\x12\x0e\n\x04\x64\x61ta\x18\x04 \x01(\x0cH\x00\x12\x1a\n\x12response_timestamp\x18\x05 \x01(\x03\x42\t\n\x07payload*\\\n\x0bMessageType\x12\r\n\tHEARTBEAT\x10\x00\x12\x13\n\x0fSERVICE_MESSAGE\x10\x01\x12\x12\n\x0e\x43LIENT_MESSAGE\x10\x02\x12\x15\n\x11\x42ROADCAST_MESSAGE\x10\x03*)\n\x12ServiceMessageType\x12\x08\n\x04SYNC\x10\x00\x12\t\n\x05\x41SYNC\x10\x01\x32P\n\rCommonService\x12?\n\x0bSendMessage\x12\x13.common.GameMessage\x1a\x1b.common.GameMessageResponseB\x10Z\x0emua/gatesvr/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016mua/gatesvr/pb'
  _globals['_MESSAGETYPE']._serialized_start=607
  _globals['_MESSAGETYPE']._serialized_end=699
  _globals['_SERVICEMESSAGETYPE']._serialized_start=701
  _globals['_SERVICEMESSAGETYPE']._serialized_end=742
  _globals['_HEADMESSAGE']._serialized_start=25
  _globals['_HEADMESSAGE']._serialized_end=311
  _globals['_GAMEMESSAGE']._serialized_start=314
  _globals['_GAMEMESSAGE']._serialized_end=456
  _globals['_GAMEMESSAGERESPONSE']._serialized_start=459
  _globals['_GAMEMESSAGERESPONSE']._serialized_end=605
  _globals['_COMMONSERVICE']._serialized_start=744
  _globals['_COMMONSERVICE']._serialized_end=824
# @@protoc_insertion_point(module_scope)
