nacos:
  addr: mse-3cb9ef30-p.nacos-ans.mse.aliyuncs.com
  port: 8848
  username: "${NACOS_USERNAME}"
  password: "${NACOS_PASSWORD}"
  service: gatesvr
  group: DEFAULT_GROUP

kafka:
  brokers:
    - alikafka-serverless-cn-0mm42ujh802-1000.alikafka.aliyuncs.com:9093
    - alikafka-serverless-cn-0mm42ujh802-2000.alikafka.aliyuncs.com:9093
    - alikafka-serverless-cn-0mm42ujh802-3000.alikafka.aliyuncs.com:9093
  caCert: ./only-4096-ca-cert
  topic: player_status_changed
  username: "alikafka_serverless-cn-0mm42ujh802"
  password: "JbuuPVcos0sAME5LtFLZFzlgrE6E3mGC"
  groupId: gatesvr-group-0

enable_token_check: true

# 服务转发配置
service_forwarding:
  # 默认负载均衡策略: round_robin 或 weighted
  default_load_balance: "weighted"
  # 请求超时时间（毫秒）
  request_timeout_ms: 5000
  # 异步请求超时时间（毫秒）
  async_timeout_ms: 1000
  # 服务特定配置
  services:
    userservice:
      group: "DEFAULT_GROUP"
      load_balance: "weighted"
      timeout_ms: 3000
    gameservice:
      group: "DEFAULT_GROUP" 
      load_balance: "round_robin"
      timeout_ms: 5000
    payservice:
      group: "prod"
      load_balance: "weighted"
      timeout_ms: 8000
    chatservice:
      group: "DEFAULT_GROUP"
      load_balance: "round_robin"
      timeout_ms: 2000

# 限流配置
rate_limit:
  # 是否启用限流保护
  enabled: true
  # 全局限流配置（整个网关）
  global_rate: 500        # 全局每秒最大请求数
  global_capacity: 1000   # 全局令牌桶容量
  # 服务级限流配置（单个服务）
  service_rate: 100       # 单服务每秒最大请求数
  service_capacity: 200   # 单服务令牌桶容量
  # 玩家级限流配置（防止单玩家恶意请求）
  player_rate: 10         # 单玩家每秒最大请求数
  player_capacity: 20     # 单玩家令牌桶容量
  # 清理配置
  cleanup_interval_min: 1 # 令牌桶清理间隔（分钟）
  bucket_idle_time_min: 5 # 令牌桶空闲超时时间（分钟）

# 认证配置
auth:
  # 是否启用认证
  enabled: true
  # JWT密钥（生产环境请使用强密钥）
  secret_key: "mua-gatesvr-jwt-secret-key-2024-production"
  # Token过期时间（小时）
  token_expire_hours: 24
  # Token清理间隔（分钟）
  cleanup_interval_min: 10
  # 需要认证的消息类型
  require_auth:
    - "SERVICE_MESSAGE"  # 服务消息需要认证
  # 免认证的服务白名单
  whitelist_services:
    - "health"      # 健康检查服务
    - "version"     # 版本查询服务
  # 单玩家最大Token数量
  max_tokens_per_player: 3
  # Token刷新配置
  enable_auto_refresh: true
  refresh_threshold_min: 5

# 连接处理配置
connection:
  first_message_timeout_sec: 5     # 首条消息超时(秒)
  read_timeout_sec: 60             # 读取超时(秒)
  write_timeout_sec: 10            # 写入超时(秒)
  enable_structured_log: true      # 启用结构化日志
  max_message_size: 4194304        # 最大消息大小(4MB)
  heartbeat_interval_sec: 30       # 心跳间隔(秒)

# Redis缓存配置（用于多gatesvr实例共享Token缓存）
enable_redis_cache: true              # 是否启用Redis缓存
redis_addr: "localhost:6379"          # Redis服务器地址
redis_password: ""                    # Redis密码（无密码留空）
redis_db: 0                          # Redis数据库索引
redis_key_prefix: "mua:token:"        # Redis键前缀
redis_pool_size: 10                  # Redis连接池大小
redis_min_idle_conns: 5              # Redis最小空闲连接数
redis_dial_timeout: 5                # Redis连接超时（秒）
redis_read_timeout: 3                # Redis读超时（秒）
redis_write_timeout: 3               # Redis写超时（秒）