// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/gomoku.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型
type MessageType int32

const (
	MessageType_UNKNOWN  MessageType = 0
	MessageType_REQUEST  MessageType = 1
	MessageType_RESPONSE MessageType = 2
	MessageType_NOTIFY   MessageType = 3
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "REQUEST",
		2: "RESPONSE",
		3: "NOTIFY",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":  0,
		"REQUEST":  1,
		"RESPONSE": 2,
		"NOTIFY":   3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gomoku_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_gomoku_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{0}
}

// 房间状态
type RoomStatus int32

const (
	RoomStatus_WAITING  RoomStatus = 0 // 等待玩家
	RoomStatus_PLAYING  RoomStatus = 1 // 游戏中
	RoomStatus_FINISHED RoomStatus = 2 // 游戏结束
)

// Enum value maps for RoomStatus.
var (
	RoomStatus_name = map[int32]string{
		0: "WAITING",
		1: "PLAYING",
		2: "FINISHED",
	}
	RoomStatus_value = map[string]int32{
		"WAITING":  0,
		"PLAYING":  1,
		"FINISHED": 2,
	}
)

func (x RoomStatus) Enum() *RoomStatus {
	p := new(RoomStatus)
	*p = x
	return p
}

func (x RoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gomoku_proto_enumTypes[1].Descriptor()
}

func (RoomStatus) Type() protoreflect.EnumType {
	return &file_proto_gomoku_proto_enumTypes[1]
}

func (x RoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomStatus.Descriptor instead.
func (RoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{1}
}

// 玩家颜色
type PlayerColor int32

const (
	PlayerColor_NONE  PlayerColor = 0
	PlayerColor_BLACK PlayerColor = 1 // 黑子，先手
	PlayerColor_WHITE PlayerColor = 2 // 白子，后手
)

// Enum value maps for PlayerColor.
var (
	PlayerColor_name = map[int32]string{
		0: "NONE",
		1: "BLACK",
		2: "WHITE",
	}
	PlayerColor_value = map[string]int32{
		"NONE":  0,
		"BLACK": 1,
		"WHITE": 2,
	}
)

func (x PlayerColor) Enum() *PlayerColor {
	p := new(PlayerColor)
	*p = x
	return p
}

func (x PlayerColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerColor) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gomoku_proto_enumTypes[2].Descriptor()
}

func (PlayerColor) Type() protoreflect.EnumType {
	return &file_proto_gomoku_proto_enumTypes[2]
}

func (x PlayerColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerColor.Descriptor instead.
func (PlayerColor) EnumDescriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{2}
}

// 游戏结果
type GameResult int32

const (
	GameResult_ONGOING   GameResult = 0 // 进行中
	GameResult_BLACK_WIN GameResult = 1 // 黑子获胜
	GameResult_WHITE_WIN GameResult = 2 // 白子获胜
	GameResult_DRAW      GameResult = 3 // 平局
)

// Enum value maps for GameResult.
var (
	GameResult_name = map[int32]string{
		0: "ONGOING",
		1: "BLACK_WIN",
		2: "WHITE_WIN",
		3: "DRAW",
	}
	GameResult_value = map[string]int32{
		"ONGOING":   0,
		"BLACK_WIN": 1,
		"WHITE_WIN": 2,
		"DRAW":      3,
	}
)

func (x GameResult) Enum() *GameResult {
	p := new(GameResult)
	*p = x
	return p
}

func (x GameResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameResult) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gomoku_proto_enumTypes[3].Descriptor()
}

func (GameResult) Type() protoreflect.EnumType {
	return &file_proto_gomoku_proto_enumTypes[3]
}

func (x GameResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameResult.Descriptor instead.
func (GameResult) EnumDescriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{3}
}

// 游戏消息
type GameMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          *MessageHead           `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	MsgType       MessageType            `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3,enum=gomoku.MessageType" json:"msg_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_proto_gomoku_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{0}
}

func (x *GameMessage) GetHead() *MessageHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GameMessage) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_UNKNOWN
}

func (x *GameMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 消息头
type MessageHead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                   // 消息ID
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`          // 玩家ID
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 服务名
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`                              // 方法名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHead) Reset() {
	*x = MessageHead{}
	mi := &file_proto_gomoku_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHead) ProtoMessage() {}

func (x *MessageHead) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHead.ProtoReflect.Descriptor instead.
func (*MessageHead) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{1}
}

func (x *MessageHead) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *MessageHead) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MessageHead) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *MessageHead) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// 游戏消息响应
type GameMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          *MessageHead           `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessageResponse) Reset() {
	*x = GameMessageResponse{}
	mi := &file_proto_gomoku_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessageResponse) ProtoMessage() {}

func (x *GameMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessageResponse.ProtoReflect.Descriptor instead.
func (*GameMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{2}
}

func (x *GameMessageResponse) GetHead() *MessageHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GameMessageResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GameMessageResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GameMessageResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 创建房间请求
type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"` // 房间名称
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                 // 房间密码（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_proto_gomoku_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *CreateRoomRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 创建房间响应
type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_proto_gomoku_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 进入房间请求
type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间ID
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`           // 房间密码（如果有）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_proto_gomoku_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 进入房间响应
type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RoomInfo      *RoomInfo              `protobuf:"bytes,3,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_proto_gomoku_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{6}
}

func (x *JoinRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinRoomResponse) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

// 离开房间请求
type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_proto_gomoku_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// 离开房间响应
type LeaveRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomResponse) Reset() {
	*x = LeaveRoomResponse{}
	mi := &file_proto_gomoku_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomResponse) ProtoMessage() {}

func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 销毁房间请求（仅房主可以）
type DestroyRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRoomRequest) Reset() {
	*x = DestroyRoomRequest{}
	mi := &file_proto_gomoku_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRoomRequest) ProtoMessage() {}

func (x *DestroyRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRoomRequest.ProtoReflect.Descriptor instead.
func (*DestroyRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{9}
}

func (x *DestroyRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// 销毁房间响应
type DestroyRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRoomResponse) Reset() {
	*x = DestroyRoomResponse{}
	mi := &file_proto_gomoku_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRoomResponse) ProtoMessage() {}

func (x *DestroyRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRoomResponse.ProtoReflect.Descriptor instead.
func (*DestroyRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{10}
}

func (x *DestroyRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DestroyRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 下棋请求
type PlacePieceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"` // X坐标（0-14）
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"` // Y坐标（0-14）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacePieceRequest) Reset() {
	*x = PlacePieceRequest{}
	mi := &file_proto_gomoku_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacePieceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacePieceRequest) ProtoMessage() {}

func (x *PlacePieceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacePieceRequest.ProtoReflect.Descriptor instead.
func (*PlacePieceRequest) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{11}
}

func (x *PlacePieceRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PlacePieceRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlacePieceRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 下棋响应
type PlacePieceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	GameState     *GameState             `protobuf:"bytes,3,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacePieceResponse) Reset() {
	*x = PlacePieceResponse{}
	mi := &file_proto_gomoku_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacePieceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacePieceResponse) ProtoMessage() {}

func (x *PlacePieceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacePieceResponse.ProtoReflect.Descriptor instead.
func (*PlacePieceResponse) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{12}
}

func (x *PlacePieceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlacePieceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PlacePieceResponse) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

// 房间信息
type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Status        RoomStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=gomoku.RoomStatus" json:"status,omitempty"`
	Players       []*PlayerInfo          `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	GameState     *GameState             `protobuf:"bytes,5,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	OwnerId       string                 `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`              // 房主ID
	CreatedTime   int64                  `protobuf:"varint,7,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"` // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_proto_gomoku_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{13}
}

func (x *RoomInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomInfo) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomInfo) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_WAITING
}

func (x *RoomInfo) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *RoomInfo) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *RoomInfo) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *RoomInfo) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

// 玩家信息
type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Color         PlayerColor            `protobuf:"varint,3,opt,name=color,proto3,enum=gomoku.PlayerColor" json:"color,omitempty"`
	IsReady       bool                   `protobuf:"varint,4,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	JoinTime      int64                  `protobuf:"varint,5,opt,name=join_time,json=joinTime,proto3" json:"join_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_proto_gomoku_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{14}
}

func (x *PlayerInfo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerInfo) GetColor() PlayerColor {
	if x != nil {
		return x.Color
	}
	return PlayerColor_NONE
}

func (x *PlayerInfo) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *PlayerInfo) GetJoinTime() int64 {
	if x != nil {
		return x.JoinTime
	}
	return 0
}

// 游戏状态
type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         []int32                `protobuf:"varint,1,rep,packed,name=board,proto3" json:"board,omitempty"`                                                 // 15x15棋盘展平为225个元素，0=空，1=黑子，2=白子
	CurrentTurn   PlayerColor            `protobuf:"varint,2,opt,name=current_turn,json=currentTurn,proto3,enum=gomoku.PlayerColor" json:"current_turn,omitempty"` // 当前该谁下棋
	Result        GameResult             `protobuf:"varint,3,opt,name=result,proto3,enum=gomoku.GameResult" json:"result,omitempty"`                               // 游戏结果
	WinnerId      string                 `protobuf:"bytes,4,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`                                   // 获胜者ID
	TotalMoves    int32                  `protobuf:"varint,5,opt,name=total_moves,json=totalMoves,proto3" json:"total_moves,omitempty"`                            // 总步数
	MoveHistory   []*Move                `protobuf:"bytes,6,rep,name=move_history,json=moveHistory,proto3" json:"move_history,omitempty"`                          // 走棋历史
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_proto_gomoku_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{15}
}

func (x *GameState) GetBoard() []int32 {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *GameState) GetCurrentTurn() PlayerColor {
	if x != nil {
		return x.CurrentTurn
	}
	return PlayerColor_NONE
}

func (x *GameState) GetResult() GameResult {
	if x != nil {
		return x.Result
	}
	return GameResult_ONGOING
}

func (x *GameState) GetWinnerId() string {
	if x != nil {
		return x.WinnerId
	}
	return ""
}

func (x *GameState) GetTotalMoves() int32 {
	if x != nil {
		return x.TotalMoves
	}
	return 0
}

func (x *GameState) GetMoveHistory() []*Move {
	if x != nil {
		return x.MoveHistory
	}
	return nil
}

// 走棋记录
type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Color         PlayerColor            `protobuf:"varint,2,opt,name=color,proto3,enum=gomoku.PlayerColor" json:"color,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	MoveNumber    int32                  `protobuf:"varint,5,opt,name=move_number,json=moveNumber,proto3" json:"move_number,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_proto_gomoku_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{16}
}

func (x *Move) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Move) GetColor() PlayerColor {
	if x != nil {
		return x.Color
	}
	return PlayerColor_NONE
}

func (x *Move) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Move) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Move) GetMoveNumber() int32 {
	if x != nil {
		return x.MoveNumber
	}
	return 0
}

func (x *Move) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 房间列表请求
type GetRoomListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomListRequest) Reset() {
	*x = GetRoomListRequest{}
	mi := &file_proto_gomoku_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomListRequest) ProtoMessage() {}

func (x *GetRoomListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomListRequest.ProtoReflect.Descriptor instead.
func (*GetRoomListRequest) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{17}
}

func (x *GetRoomListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRoomListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 房间列表响应
type GetRoomListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Rooms         []*RoomInfo            `protobuf:"bytes,2,rep,name=rooms,proto3" json:"rooms,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomListResponse) Reset() {
	*x = GetRoomListResponse{}
	mi := &file_proto_gomoku_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomListResponse) ProtoMessage() {}

func (x *GetRoomListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomListResponse.ProtoReflect.Descriptor instead.
func (*GetRoomListResponse) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{18}
}

func (x *GetRoomListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetRoomListResponse) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *GetRoomListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetRoomListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 开始游戏请求（房主发起）
type StartGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_proto_gomoku_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{19}
}

func (x *StartGameRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// 开始游戏响应
type StartGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	GameState     *GameState             `protobuf:"bytes,3,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameResponse) Reset() {
	*x = StartGameResponse{}
	mi := &file_proto_gomoku_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResponse) ProtoMessage() {}

func (x *StartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResponse.ProtoReflect.Descriptor instead.
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{20}
}

func (x *StartGameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartGameResponse) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

// 游戏状态通知（广播给房间内玩家）
type GameStateNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	GameState     *GameState             `protobuf:"bytes,2,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // MOVE, WIN, DRAW等
	EventMessage  string                 `protobuf:"bytes,4,opt,name=event_message,json=eventMessage,proto3" json:"event_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateNotify) Reset() {
	*x = GameStateNotify{}
	mi := &file_proto_gomoku_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateNotify) ProtoMessage() {}

func (x *GameStateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateNotify.ProtoReflect.Descriptor instead.
func (*GameStateNotify) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{21}
}

func (x *GameStateNotify) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameStateNotify) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *GameStateNotify) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *GameStateNotify) GetEventMessage() string {
	if x != nil {
		return x.EventMessage
	}
	return ""
}

// 玩家进出房间通知
type PlayerEventNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // JOIN, LEAVE, READY
	PlayerInfo    *PlayerInfo            `protobuf:"bytes,4,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEventNotify) Reset() {
	*x = PlayerEventNotify{}
	mi := &file_proto_gomoku_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEventNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEventNotify) ProtoMessage() {}

func (x *PlayerEventNotify) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEventNotify.ProtoReflect.Descriptor instead.
func (*PlayerEventNotify) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{22}
}

func (x *PlayerEventNotify) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PlayerEventNotify) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerEventNotify) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PlayerEventNotify) GetPlayerInfo() *PlayerInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

// 玩家准备请求
type PlayerReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerReadyRequest) Reset() {
	*x = PlayerReadyRequest{}
	mi := &file_proto_gomoku_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReadyRequest) ProtoMessage() {}

func (x *PlayerReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReadyRequest.ProtoReflect.Descriptor instead.
func (*PlayerReadyRequest) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{23}
}

func (x *PlayerReadyRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// 玩家准备响应
type PlayerReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IsReady       bool                   `protobuf:"varint,3,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`   // 当前准备状态
	RoomInfo      *RoomInfo              `protobuf:"bytes,4,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"` // 更新后的房间信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerReadyResponse) Reset() {
	*x = PlayerReadyResponse{}
	mi := &file_proto_gomoku_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReadyResponse) ProtoMessage() {}

func (x *PlayerReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReadyResponse.ProtoReflect.Descriptor instead.
func (*PlayerReadyResponse) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{24}
}

func (x *PlayerReadyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlayerReadyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PlayerReadyResponse) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *PlayerReadyResponse) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

// 获取游戏进度请求
type GetGameProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameProgressRequest) Reset() {
	*x = GetGameProgressRequest{}
	mi := &file_proto_gomoku_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameProgressRequest) ProtoMessage() {}

func (x *GetGameProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameProgressRequest.ProtoReflect.Descriptor instead.
func (*GetGameProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{25}
}

func (x *GetGameProgressRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// 获取游戏进度响应
type GetGameProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RoomInfo      *RoomInfo              `protobuf:"bytes,3,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`                 // 房间信息
	GameState     *GameState             `protobuf:"bytes,4,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`              // 游戏状态
	RemainingTime int32                  `protobuf:"varint,5,opt,name=remaining_time,json=remainingTime,proto3" json:"remaining_time,omitempty"` // 剩余时间（秒）-1表示无限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameProgressResponse) Reset() {
	*x = GetGameProgressResponse{}
	mi := &file_proto_gomoku_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameProgressResponse) ProtoMessage() {}

func (x *GetGameProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomoku_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameProgressResponse.ProtoReflect.Descriptor instead.
func (*GetGameProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_gomoku_proto_rawDescGZIP(), []int{26}
}

func (x *GetGameProgressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetGameProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGameProgressResponse) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

func (x *GetGameProgressResponse) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *GetGameProgressResponse) GetRemainingTime() int32 {
	if x != nil {
		return x.RemainingTime
	}
	return 0
}

var File_proto_gomoku_proto protoreflect.FileDescriptor

const file_proto_gomoku_proto_rawDesc = "" +
	"\n" +
	"\x12proto/gomoku.proto\x12\x06gomoku\"\x9e\x01\n" +
	"\vGameMessage\x12'\n" +
	"\x04head\x18\x01 \x01(\v2\x13.gomoku.MessageHeadR\x04head\x12.\n" +
	"\bmsg_type\x18\x02 \x01(\x0e2\x13.gomoku.MessageTypeR\amsgType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"|\n" +
	"\vMessageHead\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\"\xa4\x01\n" +
	"\x13GameMessageResponse\x12'\n" +
	"\x04head\x18\x01 \x01(\v2\x13.gomoku.MessageHeadR\x04head\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"L\n" +
	"\x11CreateRoomRequest\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"a\n" +
	"\x12CreateRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"F\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"u\n" +
	"\x10JoinRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\troom_info\x18\x03 \x01(\v2\x10.gomoku.RoomInfoR\broomInfo\"+\n" +
	"\x10LeaveRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"G\n" +
	"\x11LeaveRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x12DestroyRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"I\n" +
	"\x13DestroyRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x11PlacePieceRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"z\n" +
	"\x12PlacePieceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\n" +
	"game_state\x18\x03 \x01(\v2\x11.gomoku.GameStateR\tgameState\"\x8a\x02\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.gomoku.RoomStatusR\x06status\x12,\n" +
	"\aplayers\x18\x04 \x03(\v2\x12.gomoku.PlayerInfoR\aplayers\x120\n" +
	"\n" +
	"game_state\x18\x05 \x01(\v2\x11.gomoku.GameStateR\tgameState\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\x12!\n" +
	"\fcreated_time\x18\a \x01(\x03R\vcreatedTime\"\xa8\x01\n" +
	"\n" +
	"PlayerInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12)\n" +
	"\x05color\x18\x03 \x01(\x0e2\x13.gomoku.PlayerColorR\x05color\x12\x19\n" +
	"\bis_ready\x18\x04 \x01(\bR\aisReady\x12\x1b\n" +
	"\tjoin_time\x18\x05 \x01(\x03R\bjoinTime\"\xf4\x01\n" +
	"\tGameState\x12\x14\n" +
	"\x05board\x18\x01 \x03(\x05R\x05board\x126\n" +
	"\fcurrent_turn\x18\x02 \x01(\x0e2\x13.gomoku.PlayerColorR\vcurrentTurn\x12*\n" +
	"\x06result\x18\x03 \x01(\x0e2\x12.gomoku.GameResultR\x06result\x12\x1b\n" +
	"\twinner_id\x18\x04 \x01(\tR\bwinnerId\x12\x1f\n" +
	"\vtotal_moves\x18\x05 \x01(\x05R\n" +
	"totalMoves\x12/\n" +
	"\fmove_history\x18\x06 \x03(\v2\f.gomoku.MoveR\vmoveHistory\"\xa9\x01\n" +
	"\x04Move\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12)\n" +
	"\x05color\x18\x02 \x01(\x0e2\x13.gomoku.PlayerColorR\x05color\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x1f\n" +
	"\vmove_number\x18\x05 \x01(\x05R\n" +
	"moveNumber\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"E\n" +
	"\x12GetRoomListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x92\x01\n" +
	"\x13GetRoomListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x05rooms\x18\x02 \x03(\v2\x10.gomoku.RoomInfoR\x05rooms\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"+\n" +
	"\x10StartGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"y\n" +
	"\x11StartGameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\n" +
	"game_state\x18\x03 \x01(\v2\x11.gomoku.GameStateR\tgameState\"\xa0\x01\n" +
	"\x0fGameStateNotify\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x120\n" +
	"\n" +
	"game_state\x18\x02 \x01(\v2\x11.gomoku.GameStateR\tgameState\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12#\n" +
	"\revent_message\x18\x04 \x01(\tR\feventMessage\"\x9d\x01\n" +
	"\x11PlayerEventNotify\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x123\n" +
	"\vplayer_info\x18\x04 \x01(\v2\x12.gomoku.PlayerInfoR\n" +
	"playerInfo\"-\n" +
	"\x12PlayerReadyRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x93\x01\n" +
	"\x13PlayerReadyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bis_ready\x18\x03 \x01(\bR\aisReady\x12-\n" +
	"\troom_info\x18\x04 \x01(\v2\x10.gomoku.RoomInfoR\broomInfo\"1\n" +
	"\x16GetGameProgressRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\xd5\x01\n" +
	"\x17GetGameProgressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\troom_info\x18\x03 \x01(\v2\x10.gomoku.RoomInfoR\broomInfo\x120\n" +
	"\n" +
	"game_state\x18\x04 \x01(\v2\x11.gomoku.GameStateR\tgameState\x12%\n" +
	"\x0eremaining_time\x18\x05 \x01(\x05R\rremainingTime*A\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aREQUEST\x10\x01\x12\f\n" +
	"\bRESPONSE\x10\x02\x12\n" +
	"\n" +
	"\x06NOTIFY\x10\x03*4\n" +
	"\n" +
	"RoomStatus\x12\v\n" +
	"\aWAITING\x10\x00\x12\v\n" +
	"\aPLAYING\x10\x01\x12\f\n" +
	"\bFINISHED\x10\x02*-\n" +
	"\vPlayerColor\x12\b\n" +
	"\x04NONE\x10\x00\x12\t\n" +
	"\x05BLACK\x10\x01\x12\t\n" +
	"\x05WHITE\x10\x02*A\n" +
	"\n" +
	"GameResult\x12\v\n" +
	"\aONGOING\x10\x00\x12\r\n" +
	"\tBLACK_WIN\x10\x01\x12\r\n" +
	"\tWHITE_WIN\x10\x02\x12\b\n" +
	"\x04DRAW\x10\x032P\n" +
	"\rCommonService\x12?\n" +
	"\vSendMessage\x12\x13.gomoku.GameMessage\x1a\x1b.gomoku.GameMessageResponseB$Z\"mua/minigame/gomokusvr/internal/pbb\x06proto3"

var (
	file_proto_gomoku_proto_rawDescOnce sync.Once
	file_proto_gomoku_proto_rawDescData []byte
)

func file_proto_gomoku_proto_rawDescGZIP() []byte {
	file_proto_gomoku_proto_rawDescOnce.Do(func() {
		file_proto_gomoku_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gomoku_proto_rawDesc), len(file_proto_gomoku_proto_rawDesc)))
	})
	return file_proto_gomoku_proto_rawDescData
}

var file_proto_gomoku_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_gomoku_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_gomoku_proto_goTypes = []any{
	(MessageType)(0),                // 0: gomoku.MessageType
	(RoomStatus)(0),                 // 1: gomoku.RoomStatus
	(PlayerColor)(0),                // 2: gomoku.PlayerColor
	(GameResult)(0),                 // 3: gomoku.GameResult
	(*GameMessage)(nil),             // 4: gomoku.GameMessage
	(*MessageHead)(nil),             // 5: gomoku.MessageHead
	(*GameMessageResponse)(nil),     // 6: gomoku.GameMessageResponse
	(*CreateRoomRequest)(nil),       // 7: gomoku.CreateRoomRequest
	(*CreateRoomResponse)(nil),      // 8: gomoku.CreateRoomResponse
	(*JoinRoomRequest)(nil),         // 9: gomoku.JoinRoomRequest
	(*JoinRoomResponse)(nil),        // 10: gomoku.JoinRoomResponse
	(*LeaveRoomRequest)(nil),        // 11: gomoku.LeaveRoomRequest
	(*LeaveRoomResponse)(nil),       // 12: gomoku.LeaveRoomResponse
	(*DestroyRoomRequest)(nil),      // 13: gomoku.DestroyRoomRequest
	(*DestroyRoomResponse)(nil),     // 14: gomoku.DestroyRoomResponse
	(*PlacePieceRequest)(nil),       // 15: gomoku.PlacePieceRequest
	(*PlacePieceResponse)(nil),      // 16: gomoku.PlacePieceResponse
	(*RoomInfo)(nil),                // 17: gomoku.RoomInfo
	(*PlayerInfo)(nil),              // 18: gomoku.PlayerInfo
	(*GameState)(nil),               // 19: gomoku.GameState
	(*Move)(nil),                    // 20: gomoku.Move
	(*GetRoomListRequest)(nil),      // 21: gomoku.GetRoomListRequest
	(*GetRoomListResponse)(nil),     // 22: gomoku.GetRoomListResponse
	(*StartGameRequest)(nil),        // 23: gomoku.StartGameRequest
	(*StartGameResponse)(nil),       // 24: gomoku.StartGameResponse
	(*GameStateNotify)(nil),         // 25: gomoku.GameStateNotify
	(*PlayerEventNotify)(nil),       // 26: gomoku.PlayerEventNotify
	(*PlayerReadyRequest)(nil),      // 27: gomoku.PlayerReadyRequest
	(*PlayerReadyResponse)(nil),     // 28: gomoku.PlayerReadyResponse
	(*GetGameProgressRequest)(nil),  // 29: gomoku.GetGameProgressRequest
	(*GetGameProgressResponse)(nil), // 30: gomoku.GetGameProgressResponse
}
var file_proto_gomoku_proto_depIdxs = []int32{
	5,  // 0: gomoku.GameMessage.head:type_name -> gomoku.MessageHead
	0,  // 1: gomoku.GameMessage.msg_type:type_name -> gomoku.MessageType
	5,  // 2: gomoku.GameMessageResponse.head:type_name -> gomoku.MessageHead
	17, // 3: gomoku.JoinRoomResponse.room_info:type_name -> gomoku.RoomInfo
	19, // 4: gomoku.PlacePieceResponse.game_state:type_name -> gomoku.GameState
	1,  // 5: gomoku.RoomInfo.status:type_name -> gomoku.RoomStatus
	18, // 6: gomoku.RoomInfo.players:type_name -> gomoku.PlayerInfo
	19, // 7: gomoku.RoomInfo.game_state:type_name -> gomoku.GameState
	2,  // 8: gomoku.PlayerInfo.color:type_name -> gomoku.PlayerColor
	2,  // 9: gomoku.GameState.current_turn:type_name -> gomoku.PlayerColor
	3,  // 10: gomoku.GameState.result:type_name -> gomoku.GameResult
	20, // 11: gomoku.GameState.move_history:type_name -> gomoku.Move
	2,  // 12: gomoku.Move.color:type_name -> gomoku.PlayerColor
	17, // 13: gomoku.GetRoomListResponse.rooms:type_name -> gomoku.RoomInfo
	19, // 14: gomoku.StartGameResponse.game_state:type_name -> gomoku.GameState
	19, // 15: gomoku.GameStateNotify.game_state:type_name -> gomoku.GameState
	18, // 16: gomoku.PlayerEventNotify.player_info:type_name -> gomoku.PlayerInfo
	17, // 17: gomoku.PlayerReadyResponse.room_info:type_name -> gomoku.RoomInfo
	17, // 18: gomoku.GetGameProgressResponse.room_info:type_name -> gomoku.RoomInfo
	19, // 19: gomoku.GetGameProgressResponse.game_state:type_name -> gomoku.GameState
	4,  // 20: gomoku.CommonService.SendMessage:input_type -> gomoku.GameMessage
	6,  // 21: gomoku.CommonService.SendMessage:output_type -> gomoku.GameMessageResponse
	21, // [21:22] is the sub-list for method output_type
	20, // [20:21] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_gomoku_proto_init() }
func file_proto_gomoku_proto_init() {
	if File_proto_gomoku_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gomoku_proto_rawDesc), len(file_proto_gomoku_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gomoku_proto_goTypes,
		DependencyIndexes: file_proto_gomoku_proto_depIdxs,
		EnumInfos:         file_proto_gomoku_proto_enumTypes,
		MessageInfos:      file_proto_gomoku_proto_msgTypes,
	}.Build()
	File_proto_gomoku_proto = out.File
	file_proto_gomoku_proto_goTypes = nil
	file_proto_gomoku_proto_depIdxs = nil
}
