// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用消息头
type HeadMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ClientType    int32                  `protobuf:"varint,2,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RoleId        int64                  `protobuf:"varint,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Group         string                 `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	InstanceId    string                 `protobuf:"bytes,7,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Token         string                 `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	RequestId     string                 `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadMessage) Reset() {
	*x = HeadMessage{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadMessage) ProtoMessage() {}

func (x *HeadMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadMessage.ProtoReflect.Descriptor instead.
func (*HeadMessage) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *HeadMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *HeadMessage) GetClientType() int32 {
	if x != nil {
		return x.ClientType
	}
	return 0
}

func (x *HeadMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HeadMessage) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *HeadMessage) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HeadMessage) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *HeadMessage) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HeadMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HeadMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// 通用消息体
type GameMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgHead       *HeadMessage           `protobuf:"bytes,1,opt,name=msg_head,json=msgHead,proto3" json:"msg_head,omitempty"`
	MsgType       int32                  `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	MsgTap        string                 `protobuf:"bytes,4,opt,name=msg_tap,json=msgTap,proto3" json:"msg_tap,omitempty"`
	GameId        int32                  `protobuf:"varint,5,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *GameMessage) GetMsgHead() *HeadMessage {
	if x != nil {
		return x.MsgHead
	}
	return nil
}

func (x *GameMessage) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *GameMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameMessage) GetMsgTap() string {
	if x != nil {
		return x.MsgTap
	}
	return ""
}

func (x *GameMessage) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

// 通用回包
type GameMessageResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	MsgHead *HeadMessage           `protobuf:"bytes,1,opt,name=msg_head,json=msgHead,proto3" json:"msg_head,omitempty"`
	Ret     int32                  `protobuf:"varint,2,opt,name=ret,proto3" json:"ret,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GameMessageResponse_Reason
	//	*GameMessageResponse_Data
	Payload       isGameMessageResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessageResponse) Reset() {
	*x = GameMessageResponse{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessageResponse) ProtoMessage() {}

func (x *GameMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessageResponse.ProtoReflect.Descriptor instead.
func (*GameMessageResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *GameMessageResponse) GetMsgHead() *HeadMessage {
	if x != nil {
		return x.MsgHead
	}
	return nil
}

func (x *GameMessageResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *GameMessageResponse) GetPayload() isGameMessageResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameMessageResponse) GetReason() string {
	if x != nil {
		if x, ok := x.Payload.(*GameMessageResponse_Reason); ok {
			return x.Reason
		}
	}
	return ""
}

func (x *GameMessageResponse) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*GameMessageResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isGameMessageResponse_Payload interface {
	isGameMessageResponse_Payload()
}

type GameMessageResponse_Reason struct {
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3,oneof"`
}

type GameMessageResponse_Data struct {
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

func (*GameMessageResponse_Reason) isGameMessageResponse_Payload() {}

func (*GameMessageResponse_Data) isGameMessageResponse_Payload() {}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x06common\"\x90\x02\n" +
	"\vHeadMessage\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vclient_type\x18\x02 \x01(\x05R\n" +
	"clientType\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x17\n" +
	"\arole_id\x18\x04 \x01(\x03R\x06roleId\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05group\x18\x06 \x01(\tR\x05group\x12\x1f\n" +
	"\vinstance_id\x18\a \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05token\x18\b \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"request_id\x18\t \x01(\tR\trequestId\"\xa4\x01\n" +
	"\vGameMessage\x12.\n" +
	"\bmsg_head\x18\x01 \x01(\v2\x13.common.HeadMessageR\amsgHead\x12\x19\n" +
	"\bmsg_type\x18\x02 \x01(\x05R\amsgType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x17\n" +
	"\amsg_tap\x18\x04 \x01(\tR\x06msgTap\x12\x17\n" +
	"\agame_id\x18\x05 \x01(\x05R\x06gameId\"\x92\x01\n" +
	"\x13GameMessageResponse\x12.\n" +
	"\bmsg_head\x18\x01 \x01(\v2\x13.common.HeadMessageR\amsgHead\x12\x10\n" +
	"\x03ret\x18\x02 \x01(\x05R\x03ret\x12\x18\n" +
	"\x06reason\x18\x03 \x01(\tH\x00R\x06reason\x12\x14\n" +
	"\x04data\x18\x04 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload2P\n" +
	"\rCommonService\x12?\n" +
	"\vSendMessage\x12\x13.common.GameMessage\x1a\x1b.common.GameMessageResponseB\x19Z\x17mua/gatesvr/internal/pbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_proto_goTypes = []any{
	(*HeadMessage)(nil),         // 0: common.HeadMessage
	(*GameMessage)(nil),         // 1: common.GameMessage
	(*GameMessageResponse)(nil), // 2: common.GameMessageResponse
}
var file_common_proto_depIdxs = []int32{
	0, // 0: common.GameMessage.msg_head:type_name -> common.HeadMessage
	0, // 1: common.GameMessageResponse.msg_head:type_name -> common.HeadMessage
	1, // 2: common.CommonService.SendMessage:input_type -> common.GameMessage
	2, // 3: common.CommonService.SendMessage:output_type -> common.GameMessageResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[2].OneofWrappers = []any{
		(*GameMessageResponse_Reason)(nil),
		(*GameMessageResponse_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
