// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: gatesvr/proto/gatesvr.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallbackType int32

const (
	CallbackType_SYNC  CallbackType = 0
	CallbackType_ASYNC CallbackType = 1
	CallbackType_PUSH  CallbackType = 2
)

// Enum value maps for CallbackType.
var (
	CallbackType_name = map[int32]string{
		0: "SYNC",
		1: "ASYNC",
		2: "PUSH",
	}
	CallbackType_value = map[string]int32{
		"SYNC":  0,
		"ASYNC": 1,
		"PUSH":  2,
	}
)

func (x CallbackType) Enum() *CallbackType {
	p := new(CallbackType)
	*p = x
	return p
}

func (x CallbackType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallbackType) Descriptor() protoreflect.EnumDescriptor {
	return file_gatesvr_proto_gatesvr_proto_enumTypes[0].Descriptor()
}

func (CallbackType) Type() protoreflect.EnumType {
	return &file_gatesvr_proto_gatesvr_proto_enumTypes[0]
}

func (x CallbackType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallbackType.Descriptor instead.
func (CallbackType) EnumDescriptor() ([]byte, []int) {
	return file_gatesvr_proto_gatesvr_proto_rawDescGZIP(), []int{0}
}

// 玩家上下线事件类型
type PlayerStatusEventType int32

const (
	PlayerStatusEventType_ONLINE  PlayerStatusEventType = 0 // 上线
	PlayerStatusEventType_OFFLINE PlayerStatusEventType = 1 // 下线
)

// Enum value maps for PlayerStatusEventType.
var (
	PlayerStatusEventType_name = map[int32]string{
		0: "ONLINE",
		1: "OFFLINE",
	}
	PlayerStatusEventType_value = map[string]int32{
		"ONLINE":  0,
		"OFFLINE": 1,
	}
)

func (x PlayerStatusEventType) Enum() *PlayerStatusEventType {
	p := new(PlayerStatusEventType)
	*p = x
	return p
}

func (x PlayerStatusEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStatusEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_gatesvr_proto_gatesvr_proto_enumTypes[1].Descriptor()
}

func (PlayerStatusEventType) Type() protoreflect.EnumType {
	return &file_gatesvr_proto_gatesvr_proto_enumTypes[1]
}

func (x PlayerStatusEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStatusEventType.Descriptor instead.
func (PlayerStatusEventType) EnumDescriptor() ([]byte, []int) {
	return file_gatesvr_proto_gatesvr_proto_rawDescGZIP(), []int{1}
}

type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	CbType        CallbackType           `protobuf:"varint,3,opt,name=cb_type,json=cbType,proto3,enum=gatesvr.CallbackType" json:"cb_type,omitempty"`
	Message       *GameMessage           `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_gatesvr_proto_gatesvr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatesvr_proto_gatesvr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_gatesvr_proto_gatesvr_proto_rawDescGZIP(), []int{0}
}

func (x *PushRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PushRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PushRequest) GetCbType() CallbackType {
	if x != nil {
		return x.CbType
	}
	return CallbackType_SYNC
}

func (x *PushRequest) GetMessage() *GameMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_gatesvr_proto_gatesvr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gatesvr_proto_gatesvr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_gatesvr_proto_gatesvr_proto_rawDescGZIP(), []int{1}
}

func (x *PushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type KickPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickPlayerRequest) Reset() {
	*x = KickPlayerRequest{}
	mi := &file_gatesvr_proto_gatesvr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerRequest) ProtoMessage() {}

func (x *KickPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatesvr_proto_gatesvr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerRequest.ProtoReflect.Descriptor instead.
func (*KickPlayerRequest) Descriptor() ([]byte, []int) {
	return file_gatesvr_proto_gatesvr_proto_rawDescGZIP(), []int{2}
}

func (x *KickPlayerRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *KickPlayerRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type KickPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickPlayerResponse) Reset() {
	*x = KickPlayerResponse{}
	mi := &file_gatesvr_proto_gatesvr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerResponse) ProtoMessage() {}

func (x *KickPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gatesvr_proto_gatesvr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerResponse.ProtoReflect.Descriptor instead.
func (*KickPlayerResponse) Descriptor() ([]byte, []int) {
	return file_gatesvr_proto_gatesvr_proto_rawDescGZIP(), []int{3}
}

func (x *KickPlayerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KickPlayerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ForwardMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardMessageRequest) Reset() {
	*x = ForwardMessageRequest{}
	mi := &file_gatesvr_proto_gatesvr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardMessageRequest) ProtoMessage() {}

func (x *ForwardMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatesvr_proto_gatesvr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardMessageRequest.ProtoReflect.Descriptor instead.
func (*ForwardMessageRequest) Descriptor() ([]byte, []int) {
	return file_gatesvr_proto_gatesvr_proto_rawDescGZIP(), []int{4}
}

func (x *ForwardMessageRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ForwardMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ForwardMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardMessageResponse) Reset() {
	*x = ForwardMessageResponse{}
	mi := &file_gatesvr_proto_gatesvr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardMessageResponse) ProtoMessage() {}

func (x *ForwardMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gatesvr_proto_gatesvr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardMessageResponse.ProtoReflect.Descriptor instead.
func (*ForwardMessageResponse) Descriptor() ([]byte, []int) {
	return file_gatesvr_proto_gatesvr_proto_rawDescGZIP(), []int{5}
}

func (x *ForwardMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 游戏通用消息
type GameMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgType       int32                  `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`          // 消息类型/标签
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                          // 业务数据
	ClientType    int32                  `protobuf:"varint,4,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"` // 客户端类型 1.android/2.ios/3.pc/4.minigame/5.web/6.harmonyOS
	RoleId        int64                  `protobuf:"varint,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`             // 游戏角色id
	MsgTap        int32                  `protobuf:"varint,6,opt,name=msg_tap,json=msgTap,proto3" json:"msg_tap,omitempty"`             // 消息标签 用于未来业务消息转发
	GameId        int32                  `protobuf:"varint,7,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`             // 游戏id 用于未来业务消息转发
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_gatesvr_proto_gatesvr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gatesvr_proto_gatesvr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_gatesvr_proto_gatesvr_proto_rawDescGZIP(), []int{6}
}

func (x *GameMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GameMessage) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *GameMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameMessage) GetClientType() int32 {
	if x != nil {
		return x.ClientType
	}
	return 0
}

func (x *GameMessage) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *GameMessage) GetMsgTap() int32 {
	if x != nil {
		return x.MsgTap
	}
	return 0
}

func (x *GameMessage) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

// 玩家上下线事件消息
type PlayerStatusChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`               // 玩家ID
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`                                           // 客户端IP地址
	Event         PlayerStatusEventType  `protobuf:"varint,3,opt,name=event,proto3,enum=gatesvr.PlayerStatusEventType" json:"event,omitempty"` // 事件类型：上线/下线
	EventTime     int64                  `protobuf:"varint,4,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`           // 事件时间（时间戳，单位秒或毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStatusChanged) Reset() {
	*x = PlayerStatusChanged{}
	mi := &file_gatesvr_proto_gatesvr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStatusChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatusChanged) ProtoMessage() {}

func (x *PlayerStatusChanged) ProtoReflect() protoreflect.Message {
	mi := &file_gatesvr_proto_gatesvr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatusChanged.ProtoReflect.Descriptor instead.
func (*PlayerStatusChanged) Descriptor() ([]byte, []int) {
	return file_gatesvr_proto_gatesvr_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerStatusChanged) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerStatusChanged) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PlayerStatusChanged) GetEvent() PlayerStatusEventType {
	if x != nil {
		return x.Event
	}
	return PlayerStatusEventType_ONLINE
}

func (x *PlayerStatusChanged) GetEventTime() int64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

var File_gatesvr_proto_gatesvr_proto protoreflect.FileDescriptor

const file_gatesvr_proto_gatesvr_proto_rawDesc = "" +
	"\n" +
	"\x1bgatesvr/proto/gatesvr.proto\x12\agatesvr\"\x9a\x01\n" +
	"\vPushRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12.\n" +
	"\acb_type\x18\x03 \x01(\x0e2\x15.gatesvr.CallbackTypeR\x06cbType\x12.\n" +
	"\amessage\x18\x04 \x01(\v2\x14.gatesvr.GameMessageR\amessage\"B\n" +
	"\fPushResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x11KickPlayerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"H\n" +
	"\x12KickPlayerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\x15ForwardMessageRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"L\n" +
	"\x16ForwardMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcb\x01\n" +
	"\vGameMessage\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x19\n" +
	"\bmsg_type\x18\x02 \x01(\x05R\amsgType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1f\n" +
	"\vclient_type\x18\x04 \x01(\x05R\n" +
	"clientType\x12\x17\n" +
	"\arole_id\x18\x05 \x01(\x03R\x06roleId\x12\x17\n" +
	"\amsg_tap\x18\x06 \x01(\x05R\x06msgTap\x12\x17\n" +
	"\agame_id\x18\a \x01(\x05R\x06gameId\"\x97\x01\n" +
	"\x13PlayerStatusChanged\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x124\n" +
	"\x05event\x18\x03 \x01(\x0e2\x1e.gatesvr.PlayerStatusEventTypeR\x05event\x12\x1d\n" +
	"\n" +
	"event_time\x18\x04 \x01(\x03R\teventTime*-\n" +
	"\fCallbackType\x12\b\n" +
	"\x04SYNC\x10\x00\x12\t\n" +
	"\x05ASYNC\x10\x01\x12\b\n" +
	"\x04PUSH\x10\x02*0\n" +
	"\x15PlayerStatusEventType\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x00\x12\v\n" +
	"\aOFFLINE\x10\x012\xe0\x01\n" +
	"\aGateSvr\x12E\n" +
	"\n" +
	"KickPlayer\x12\x1a.gatesvr.KickPlayerRequest\x1a\x1b.gatesvr.KickPlayerResponse\x12Q\n" +
	"\x0eForwardMessage\x12\x1e.gatesvr.ForwardMessageRequest\x1a\x1f.gatesvr.ForwardMessageResponse\x12;\n" +
	"\fPushToClient\x12\x14.gatesvr.PushRequest\x1a\x15.gatesvr.PushResponseB\x10Z\x0einternal/pb;pbb\x06proto3"

var (
	file_gatesvr_proto_gatesvr_proto_rawDescOnce sync.Once
	file_gatesvr_proto_gatesvr_proto_rawDescData []byte
)

func file_gatesvr_proto_gatesvr_proto_rawDescGZIP() []byte {
	file_gatesvr_proto_gatesvr_proto_rawDescOnce.Do(func() {
		file_gatesvr_proto_gatesvr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gatesvr_proto_gatesvr_proto_rawDesc), len(file_gatesvr_proto_gatesvr_proto_rawDesc)))
	})
	return file_gatesvr_proto_gatesvr_proto_rawDescData
}

var file_gatesvr_proto_gatesvr_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gatesvr_proto_gatesvr_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gatesvr_proto_gatesvr_proto_goTypes = []any{
	(CallbackType)(0),              // 0: gatesvr.CallbackType
	(PlayerStatusEventType)(0),     // 1: gatesvr.PlayerStatusEventType
	(*PushRequest)(nil),            // 2: gatesvr.PushRequest
	(*PushResponse)(nil),           // 3: gatesvr.PushResponse
	(*KickPlayerRequest)(nil),      // 4: gatesvr.KickPlayerRequest
	(*KickPlayerResponse)(nil),     // 5: gatesvr.KickPlayerResponse
	(*ForwardMessageRequest)(nil),  // 6: gatesvr.ForwardMessageRequest
	(*ForwardMessageResponse)(nil), // 7: gatesvr.ForwardMessageResponse
	(*GameMessage)(nil),            // 8: gatesvr.GameMessage
	(*PlayerStatusChanged)(nil),    // 9: gatesvr.PlayerStatusChanged
}
var file_gatesvr_proto_gatesvr_proto_depIdxs = []int32{
	0, // 0: gatesvr.PushRequest.cb_type:type_name -> gatesvr.CallbackType
	8, // 1: gatesvr.PushRequest.message:type_name -> gatesvr.GameMessage
	1, // 2: gatesvr.PlayerStatusChanged.event:type_name -> gatesvr.PlayerStatusEventType
	4, // 3: gatesvr.GateSvr.KickPlayer:input_type -> gatesvr.KickPlayerRequest
	6, // 4: gatesvr.GateSvr.ForwardMessage:input_type -> gatesvr.ForwardMessageRequest
	2, // 5: gatesvr.GateSvr.PushToClient:input_type -> gatesvr.PushRequest
	5, // 6: gatesvr.GateSvr.KickPlayer:output_type -> gatesvr.KickPlayerResponse
	7, // 7: gatesvr.GateSvr.ForwardMessage:output_type -> gatesvr.ForwardMessageResponse
	3, // 8: gatesvr.GateSvr.PushToClient:output_type -> gatesvr.PushResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gatesvr_proto_gatesvr_proto_init() }
func file_gatesvr_proto_gatesvr_proto_init() {
	if File_gatesvr_proto_gatesvr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gatesvr_proto_gatesvr_proto_rawDesc), len(file_gatesvr_proto_gatesvr_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gatesvr_proto_gatesvr_proto_goTypes,
		DependencyIndexes: file_gatesvr_proto_gatesvr_proto_depIdxs,
		EnumInfos:         file_gatesvr_proto_gatesvr_proto_enumTypes,
		MessageInfos:      file_gatesvr_proto_gatesvr_proto_msgTypes,
	}.Build()
	File_gatesvr_proto_gatesvr_proto = out.File
	file_gatesvr_proto_gatesvr_proto_goTypes = nil
	file_gatesvr_proto_gatesvr_proto_depIdxs = nil
}
